name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: |
          pytest --cov-report xml:coverage.xml --cov=mylib/ tests/unit_tests
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
          echo $sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g'         
      - name: upload cov.xml from pytest
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
          retention-days: 1
  sonar_cloud:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: download cov.xml from pytest action
      uses: actions/download-artifact@v3
      with:
        name: coverage
    - name: pwd 1
      run: |
        pwd
        ls
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: pwd 2
      run: |
        pwd
        ls